// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_A1_SigmaU1_lehmer
Rcpp::List build_A1_SigmaU1_lehmer(const Rcpp::IntegerMatrix& ContTable);
RcppExport SEXP _NCor_build_A1_SigmaU1_lehmer(SEXP ContTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type ContTable(ContTableSEXP);
    rcpp_result_gen = Rcpp::wrap(build_A1_SigmaU1_lehmer(ContTable));
    return rcpp_result_gen;
END_RCPP
}
// build_A2_SigmaU2_lehmer
Rcpp::List build_A2_SigmaU2_lehmer(const Rcpp::IntegerMatrix& ContTable);
RcppExport SEXP _NCor_build_A2_SigmaU2_lehmer(SEXP ContTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type ContTable(ContTableSEXP);
    rcpp_result_gen = Rcpp::wrap(build_A2_SigmaU2_lehmer(ContTable));
    return rcpp_result_gen;
END_RCPP
}
// fill_matrix_max_tbb_lehmer_cpp
Rcpp::List fill_matrix_max_tbb_lehmer_cpp(const Rcpp::NumericMatrix& ContScaled_, double eps, Rcpp::Nullable<Rcpp::NumericVector> max_perms_, int num_threads);
RcppExport SEXP _NCor_fill_matrix_max_tbb_lehmer_cpp(SEXP ContScaled_SEXP, SEXP epsSEXP, SEXP max_perms_SEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type ContScaled_(ContScaled_SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type max_perms_(max_perms_SEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_matrix_max_tbb_lehmer_cpp(ContScaled_, eps, max_perms_, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// max_gamma_nominal_cont_dp_parallel
List max_gamma_nominal_cont_dp_parallel(const IntegerVector& x, const NumericVector& y, int K, double tol, int num_threads);
RcppExport SEXP _NCor_max_gamma_nominal_cont_dp_parallel(SEXP xSEXP, SEXP ySEXP, SEXP KSEXP, SEXP tolSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(max_gamma_nominal_cont_dp_parallel(x, y, K, tol, num_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NCor_build_A1_SigmaU1_lehmer", (DL_FUNC) &_NCor_build_A1_SigmaU1_lehmer, 1},
    {"_NCor_build_A2_SigmaU2_lehmer", (DL_FUNC) &_NCor_build_A2_SigmaU2_lehmer, 1},
    {"_NCor_fill_matrix_max_tbb_lehmer_cpp", (DL_FUNC) &_NCor_fill_matrix_max_tbb_lehmer_cpp, 4},
    {"_NCor_max_gamma_nominal_cont_dp_parallel", (DL_FUNC) &_NCor_max_gamma_nominal_cont_dp_parallel, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_NCor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
