# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_A1_SigmaU1_lehmer <- function(ContTable) {
    .Call(`_NCor_build_A1_SigmaU1_lehmer`, ContTable)
}

build_A2_SigmaU2_lehmer <- function(ContTable) {
    .Call(`_NCor_build_A2_SigmaU2_lehmer`, ContTable)
}

fill_matrix_max_tbb_lehmer_cpp <- function(ContScaled_, eps = 1e-15, max_perms_ = NULL, num_threads = -1L) {
    .Call(`_NCor_fill_matrix_max_tbb_lehmer_cpp`, ContScaled_, eps, max_perms_, num_threads)
}

max_gamma_nominal_cont_dp_parallel <- function(x, y, K, tol = 0.0, num_threads = 0L) {
    .Call(`_NCor_max_gamma_nominal_cont_dp_parallel`, x, y, K, tol, num_threads)
}

